### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party'

### ISSUE THREAD

**Issue by PoulamiSM** [facebookresearch/CutLER#50]
While trying to run maskcut/demo.py, this error is repeatedly encountered: 
ModuleNotFoundError: No module named 'third_party'
The git submodules have been all updated, still the error persists.
This error is also encountered in the Colab notebook for MaskCut. 

Any suggestions to fix the issue?

**Comment by bjoved00** [comment]
Hi, I have the same error as you. I just fixed it by copying the folder "third_party" from the Colab notebook to my local CutLER folder, as I noticed the folder "TokenCut" inside it was actually empty. This solved the error for me, however I got a different one.

**Comment by frank-xwang** [comment]
Hey, you may want to follow our [INSTALL.md](https://github.com/facebookresearch/CutLER/blob/ff8373f85e64fa4a66ebde4572b61215f2078f6e/INSTALL.md) to prepare the necessary environment and git clone all necessary packages. The third party folder is empty because you may didn't use the --recursive argument when cloning our codebase:

git clone --recursive [git@github.com](mailto:git@github.com):facebookresearch/CutLER.git

This command will automatically download all the necessary third-party codes alongside the main repository.
